const ROUTES = [
  {
    id: 'tues-dv',
    tabName: 'Tues DV',
    day: 'Tuesday',
    name: 'Valley Route',
    color: '#3d7f91',
    colorDark: '#2f6473',
    colorLight: '#1c3a43',
  },
  {
    id: 'tues-4wd',
    tabName: 'TUES 4WD ACTION',
    day: 'Tuesday',
    name: '4WD Action',
    color: '#a06a3e',
    colorDark: '#805431',
    colorLight: '#4a3120',
  },
  {
    id: 'weds-res',
    tabName: 'Weds DV Res',
    day: 'Wednesday',
    name: 'Valley Residential',
    color: '#4a8a5e',
    colorDark: '#3a6e4b',
    colorLight: '#22402d',
  },
  {
    id: 'weds-commercial',
    tabName: 'Weds Commercial',
    day: 'Wednesday',
    name: 'Commercial',
    color: '#6e5f8a',
    colorDark: '#584c6e',
    colorLight: '#332d40',
  },
  {
    id: 'thurs-uv',
    tabName: 'Thurs UV',
    day: 'Thursday',
    name: 'Upper Valley',
    color: '#3f8a80',
    colorDark: '#326e66',
    colorLight: '#1e403c',
  },
  {
    id: 'thurs-comeagle',
    tabName: 'Thursday COM/EAGLE',
    day: 'Thursday',
    name: 'Com / Eagle',
    color: '#9a5b52',
    colorDark: '#7b4842',
    colorLight: '#472a26',
  },
  {
    id: 'friday',
    tabName: 'Friday',
    day: 'Friday',
    name: 'Friday Route',
    color: '#8a7c42',
    colorDark: '#6e6335',
    colorLight: '#403a1f',
  },
  {
    id: 'monday',
    tabName: 'Monday',
    day: 'Monday',
    name: 'Monday Route',
    color: '#8a5a70',
    colorDark: '#6e485a',
    colorLight: '#402935',
  },
  {
    id: 'max-routes',
    tabName: 'Max Routes',
    day: 'Daily',
    name: 'Max Routes',
    color: '#5a6a8a',
    colorDark: '#48556e',
    colorLight: '#2a3140',
  },
];
